### ISSUE TITLE
Philips Run LC

### ISSUE THREAD

**Issue by jhamilx** [openmrslab/suspect#100]
Hi,

Was wondering if anyone else had run into this problem:

 When writing data to RAW files from Philips data I generally get an INITIA 3 error. (This is after aligning and suppressing water signal) if one does not do preprocessing LC model is unable to align/phase the data. INITIA 3 has to do with axis range (bad minima) however the axis produced from the SDAT by suspect fits the bill as far as LC model's written requirements. I am asking the LC Model folks about this as well.

**Comment by bennyrowland** [comment]
@jhamilx is there any chance you can let me have an example sdat/spar pair where you have this problem (or ideally some minimal code that reproduces the issue) so I can take a look at it. I haven't done much work with Philips data myself so there may be some issues with the way the library handles it, although that does seem like a strange error. The .raw file shouldn't be the problem, the INITIA 3 error seems to relate to the PPMST or PPMEND, or possibly DELTAT, which are all in the .control file. Someone else has recently told me about an issue with the frequency axis in LCModel being incorrect, so this might be the same problem, although that was for Siemens data.

**Comment by bennyrowland** [comment]
@jhamilx another question for you - are you using the `write_all_files()` function to generate a .RAW and a .CONTROL file and using the command line to process them, or are you using `save_raw()` and then processing in lcmgui? The .RAW file format is missing essential information required for processing the file, particularly the DELTAT and NUNFIL parameters, which are supplied by the .CONTROL file. When reading files from other manufacturers in to lcmgui, it automatically parses these parameters out of the file, but it is impossible to do the same from the .RAW format. I have no idea why Dr Provencher decided to do it that way, but it means that it is easy to process files through lcmgui using default (and incorrect) values for DELTAT and NUNFIL, which would result in an incorrect x-axis and the kind of problems you are seeing.

**Comment by jhamilx** [comment]
@bennyrowland  I can send you the version with a very similar problem. Removing my alignment routine and writing just the data that Suspect pulls from the SDAT, I have a phasing problem caused, I believe by LC Models phasing routine because the data that suspect pulls looks perfect.

![image](https://user-images.githubusercontent.com/26006773/35874178-db2169fc-0b39-11e8-898c-d1c8c1ff4166.png)


I am using write_all_files and then processing using the command line. I can send you the data once I clean it quickly and will send some sample code but essentially it is:

**Comment by jhamilx** [comment]
Files attached.

[zip.zip](https://github.com/openmrslab/suspect/files/1700144/zip.zip)

**Comment by jhamilx** [comment]
I should note that setting:

SDDEGZ = 5.0
SDDEGP = 3.0

Gave me a proper spectra, but I am unable to shift so that NAA main peak is 2 and so on.

@bennyrowland

I actually was able to fix this by modifying the deltat parameter as well to:

4.0e-04

Any ideas on how this might be dynamically calculated or pulled from the file. I've been digging through the parameter_dict to find similar values.

**Comment by bennyrowland** [comment]
@jhamilx I checked through the code and discovered that the dt for sdat data was actually hard coded to be 0.5ms, rather than being read out of the file. I have fixed this in the master, can you test it out to make sure that fixes your problem?

**Comment by jhamilx** [comment]
Hi Ben,

I probably made the same change as you locally. I did 1/parameter_dict["sample_frequency"], if thats the change you made I can confirm it works.
