### ISSUE TITLE
trouble with reading in data

### ISSUE THREAD

**Issue by felicitasH** [openmrslab/suspect#115]
<img width="1083" alt="screen shot 2018-06-25 at 15 52 38" src="https://user-images.githubusercontent.com/40580965/41876014-873f910a-789a-11e8-8121-a8753564cd64.png">
I was trying to use the data but got this error message right away, I already re-downloaded the data but the error message stays the same, I'd be happy about any help or ideas what might be the issue here
Thanks!!

**Comment by bennyrowland** [comment]
Hi @felicitasH,
Thanks for getting in touch about this. Loading files is one of the most difficult parts of the code to get right, as we can only test on the files we have available. In this case, I believe that the problem is with the encoding being used to read the .spar text file. The default encoding is utf-8, which has worked for the .spar files I have used in the past, but probably the true encoding is something different, which is heavily overlapped with utf-8 but not exactly the same, so it works sometimes and sometimes not.

Are you able to share the .SPAR file you are using with me (e.g. anonymised etc.). This would be the quickest way to resolve the problem as I can then figure out the correct encoding and update the library to fix the problem. If not, I will speak to my contacts at Philips and ask them about the encoding used, but they may take a little longer to respond to that.

Also, welcome to the Suspect community. I hope that once this problem is solved the library is useful for you, and please do ask any questions you have and/or make feature requests, it is through community participation that we become better and more useful.

Ben

**Comment by felicitasH** [comment]
Hi Ben,

Thank you so much for the immediate response, I really appreciate the help! I will talk to the people that have provided me the data and see if I am able to send you one of the files, as it turns out I get this error message for 5 cases out of a 43 case strong sample, so it would be great to get to the bottom of this error. If you wouldn’t mind asking your contacts at Philips I would really appreciate it!

I’ll get back to you once I have figured out if I can send you a sample case!

Cheers

Fee

On 25. Jun 2018, at 17:22, Ben Rowland <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @felicitasH<https://github.com/felicitasH>,
Thanks for getting in touch about this. Loading files is one of the most difficult parts of the code to get right, as we can only test on the files we have available. In this case, I believe that the problem is with the encoding being used to read the .spar text file. The default encoding is utf-8, which has worked for the .spar files I have used in the past, but probably the true encoding is something different, which is heavily overlapped with utf-8 but not exactly the same, so it works sometimes and sometimes not.

Are you able to share the .SPAR file you are using with me (e.g. anonymised etc.). This would be the quickest way to resolve the problem as I can then figure out the correct encoding and update the library to fix the problem. If not, I will speak to my contacts at Philips and ask them about the encoding used, but they may take a little longer to respond to that.

Also, welcome to the Suspect community. I hope that once this problem is solved the library is useful for you, and please do ask any questions you have and/or make feature requests, it is through community participation that we become better and more useful.

Ben

**Comment by felicitasH** [comment]
Hi Ben,

So I talked with everyone and was able to send you the files, this is another case that gave me the error message that I took a screenshot from, please let me know if there is anything else I can do and thank you very much for looking into this!!


Cheers

Fee



On 29. Jun 2018, at 10:30, Felicitas Heinen <feeheinen@hotmail.de<mailto:feeheinen@hotmail.de>> wrote:

Hi Ben,

Thank you so much for the immediate response, I really appreciate the help! I will talk to the people that have provided me the data and see if I am able to send you one of the files, as it turns out I get this error message for 5 cases out of a 43 case strong sample, so it would be great to get to the bottom of this error. If you wouldn’t mind asking your contacts at Philips I would really appreciate it!

I’ll get back to you once I have figured out if I can send you a sample case!

Cheers

Fee

On 25. Jun 2018, at 17:22, Ben Rowland <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @felicitasH<https://github.com/felicitasH>,
Thanks for getting in touch about this. Loading files is one of the most difficult parts of the code to get right, as we can only test on the files we have available. In this case, I believe that the problem is with the encoding being used to read the .spar text file. The default encoding is utf-8, which has worked for the .spar files I have used in the past, but probably the true encoding is something different, which is heavily overlapped with utf-8 but not exactly the same, so it works sometimes and sometimes not.

Are you able to share the .SPAR file you are using with me (e.g. anonymised etc.). This would be the quickest way to resolve the problem as I can then figure out the correct encoding and update the library to fix the problem. If not, I will speak to my contacts at Philips and ask them about the encoding used, but they may take a little longer to respond to that.

Also, welcome to the Suspect community. I hope that once this problem is solved the library is useful for you, and please do ask any questions you have and/or make feature requests, it is through community participation that we become better and more useful.

Ben

**Comment by bennyrowland** [comment]
Hi @felicitasH,
The latest release of Suspect (v0.3.9) has an option to specify different encodings when loading sdat/spar files using the spar_encoding parameter. Can you please let me know whether this fixes your problem?
Thanks,
Ben
