### ISSUE TITLE
Anonymize_twix 

### ISSUE THREAD

**Issue by JWSica** [openmrslab/suspect#168]
Hi! I am looking for some help in running the script to anonymize twix files. I tried running "anonymize.py" script and it did not make any changes to my file. I also found "Twix.py" which had additional steps that I am not familiar with. I had installed openmrslab and Docker to run it. However, I never used either and had just followed the instruction as documented to set it up.

Has anyone use either script and was able to execute it? I want to make sure the scan date within the twix file is also de-identified. 

I am completely new to this so I am at a lost on how to proceed...

Thank you,
Jessica

**Comment by darrencl** [comment]
Hi Jessica, 

I have just tested this myself and I don't think you would need to setup openmrslab and Docker to run this. Once you installed suspect in your Python, you can run the `anonymize_twix [twix_path] [result_path]` command in command line/terminal interface. In my example below, I have `qa_twix.dat` that I want to anonymize as `anon_twix.dat` in the same folder. 
```
anonymize_twix qa_twix.dat anon_twix.dat
```

Hope this helps.

**Comment by darrencl** [comment]
I will close this for now. Feel free to re-open if that doesn't solve your problem.
