### ISSUE TITLE
DOC: Write water suppression documentation

### ISSUE THREAD

**Issue by bennyrowland** [openmrslab/suspect#28]

**Comment by jhamilx** [comment]
When will this be released, would be very helpful.

**Comment by bennyrowland** [comment]
@jhamilx, thanks for reminding me to get on with this. I have now posted a new tutorial on this topic, please have a look and let me know what you think. Do you find the mixed code / explanation notebooks helpful, or would you rather just have code examples?

**Comment by jhamilx** [comment]
No worries, yeah the notebooks are good. Really either is fine though.
