### ISSUE TITLE
Spectrsocopy and Image

### ISSUE THREAD

**Issue by jhamilx** [openmrslab/suspect#42]
right now can the image module be used in some way  to correlate MRS data instance with voxel locations? Sorry I am very new to dicom.

**Comment by bennyrowland** [comment]
The image module is designed to load a set of dicom images into a 3d numpy array, along with the transformation matrix into scanner space. This can be used to draw MRS voxels on top of the structural images, for example. At the moment the interface is very clunky, I am working on improving the way that this works and should have something working in the next couple of weeks. Let me know if you need something sooner than that and I can give you a quick run down of the existing options.

**Comment by bennyrowland** [comment]
@jhamilx the latest version of the code now supports drawing MRS voxels on top of DICOM images. To get the latest version you can use pip install --upgrade https://github.com/openmrslab/suspect/archive/master.zip
There is a tutorial notebook in place on readthedocs to explain how to do everything. Any feedback would be appreciated.

**Comment by bennyrowland** [comment]
@jhamilx - did the new changes solve your issue? If you don't need anything else for now then I will close this issue.
