### ISSUE TITLE
Coordinate File Spectra Format

### ISSUE THREAD

**Issue by jhamilx** [openmrslab/suspect#97]
With LC Model, what format are the spectra in from the Coordinate files? FFT or plot produces nothing meaningful.

**Comment by bennyrowland** [comment]
Hi @jhamilx, I am afraid you will have to be a little bit more specific about your issue. Have you successfully run LCModel on some data, which has produced a .coord file? The .coord file contains at the least a set of ppm values for the x-axis, the phased and filtered data, the fit to that data and the baseline. Depending on how you set up the processing it may also contain individual fits for some of the metabolites in the basis set. All data is in the frequency domain, however it is also only for a restricted region of the overall spectrum, typically from about 4.2 to 0ppm, so the data is not the same as the input data for processing.

If you use the suspect.io.lcmodel.read_coord() function that should take a .coord filename as input and return a dict containing all the various bits of data that are contained in the file, you should be able to plot e.g. the data value and immediately see a spectrum. If the results of plotting this are not as you expect, it may be worth checking some of the other LCModel output files such as the .table file to make sure that the fitting has worked correctly. 

If you have a particular .coord file that is giving you problems and you can share it, I would be very happy to take a look and make sure that Suspect is able to support it correctly.

**Comment by jhamilx** [comment]
Thanks Ben, understood.
